# Generated by Django 5.2.9 on 2025-12-24 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sray', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-vote_count'], 'verbose_name': 'Кандидат', 'verbose_name_plural': 'Кандидаты'},
        ),
        migrations.AlterModelOptions(
            name='nomination',
            options={'ordering': ['-created_at'], 'verbose_name': 'Номинация', 'verbose_name_plural': 'Номинации'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-voted_at'], 'verbose_name': 'Голос', 'verbose_name_plural': 'Голоса'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nomination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nominations/', verbose_name='Изображение номинации'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='voting_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания голосования'),
        ),
    ]
